CREATE TABLE US_ROLE 
(
  ID NUMBER(*, 0) NOT NULL 
, NAME NVARCHAR2(50) NOT NULL 
, IDSTATE NUMBER(*, 0) NOT NULL 
, USERCREATE NVARCHAR2(50) NOT NULL 
, DATECREATE DATE NOT NULL 
, USERUPDATE NVARCHAR2(50) 
, DATEUPDATE DATE 
, CONSTRAINT US_ROLE_PK PRIMARY KEY 
  (
    ID 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX US_ROLE_PK ON US_ROLE (ID ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

ALTER TABLE US_ROLE
ADD CONSTRAINT US_ROLE_FK1 FOREIGN KEY
(
  IDSTATE 
)
REFERENCES US_STATE
(
  ID 
)
ENABLE;
